### ISSUE TITLE
Incorrect content-type in GET /stations documentation

### ISSUE THREAD

**Issue by debfx** [derhuerst/db-rest#11]
First of all thanks a lot for providing this API!

I noticed that docs/index.md says GET /stations returns Content-Type: application/json but in fact returns newline separated JSON.

(As a side node: IMHO it would be easier to use if it did return a JSON list instead)

**Comment by derhuerst** [comment]
Thanks for reporting, fixed in 84ea402!

>IMHO it would be easier to use if it did return a JSON list instead

Yes, for some use cases it is indeed easier. I think having both is useful; newline-separated JSON works very well with large data sets, as it can be consumed in a streaming way, split up at any point, etc.

Let's see when I have the time to rework [`hafas-rest-api`](https://github.com/derhuerst/hafas-rest-api), the lib beneath `db-rest`.
