### ISSUE TITLE
db-rest serves vbb-rest page

### ISSUE THREAD

**Issue by flip111** [derhuerst/db-rest#15]
When going to the launched server at `2.db.transport.rest:3000` i get a page saying:

```
vbb-rest

An HTTP API for Berlin & Brandenburg public transport.

documentation
```

I thought this repo was for the trains in germany, what's going on?

**Comment by derhuerst** [comment]
> When going to the launched server at `2.db.transport.rest:3000` i get a page saying [`vbb-`rest`] [...].

Yes, this due to how I run the `*.transport.rest` API endpoints internally: I run each of them on a different local port (`a.3.vbb.transport.rest` on `3000`, `a.2.bvg.transport.rest` on `3001`, etc) and reverse-proxy them on `443`.

I agree that this is very unintuitive, and this way I expose a plain HTTP endpoint to the public, so I will fix this.

**Comment by derhuerst** [comment]
Okay, these ports are blocked now. Thanks for reporting!

**Comment by derhuerst** [comment]
> When going to the launched server at `2.db.transport.rest:3000` [...].

I'm curious: Where did you get that host from? Because you started `db-rest` locally and it said "Listening on 2.db.transport.rest:3000"?

**Comment by flip111** [comment]
```
» npm start

> db-rest@2.0.0 start /home/flip111/js/db-rest
> node index.js

Listening on 2.db.transport.rest:3000.
```

How can i access the right API ? is it on port 443 ?

**Comment by derhuerst** [comment]
If you start the API from the Git repo locally, it will listen on `localhost:3000`. The `2.db.transport.rest` part is wrong.
